#%RAML 1.0 DataType

type: object

properties:
  user_id:
    description: Pataient ID
    type: integer
  doctor_id:
    description: Doctor ID
    type: integer
  hospital_id:
    description: Hospital ID
    type: integer
  date:
    type: date-only
  specialization_id:
    description: Specialization Name
    type: integer
  start_time:
    description: Preferred Start Time
    type: time-only
  end_time?:
    description: Preferred End Time
    type: time-only
  symptoms:
    description: Add symptoms description.
    type: string
  added_by:
    type: integer


     
    
