#%RAML 1.0 DataType

type: object
    
properties:
  patient_id:
    type: integer
  first_name?:
    description: Patient first name.
    type: string
    minLength: 3
    maxLength: 25
  last_name?:
    description: Patient last name.
    type: string
    minLength: 3
    maxLength: 25
  email?: 
    description: Patient email.
    type: string
    pattern: ^.+@.+\..+$
    minLength: 5
    maxLength: 50
  phone_number?:
    description: Patient phone number.
    type: string  
    minLength: 10
    maxLength: 12   
  age?: 
    description: Patient age.
    type: integer
    minimum: 0
  gender?:
   enum: ["male", "female", "other"]
  address?:
    description: Add patient Address.
    type: string
  guardian_name?:
    description: Add guardian name.
    type: string
    minLength: 3
    maxLength: 25
  guardian_phone_number?:
    description: Add guardian phone number.
    type: string
    minLength: 10
    maxLength: 12
  updated_at :
    type: datetime-only